// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Pokemon struct {
	ID            pgtype.Int8
	NameEnglish   pgtype.Text
	NameJapanese  pgtype.Text
	NameChinese   pgtype.Text
	NameFrench    pgtype.Text
	Types         []string
	BaseHp        pgtype.Int8
	BaseAttack    pgtype.Int8
	BaseDefense   pgtype.Int8
	BaseSpAttack  pgtype.Int8
	BaseSpDefense pgtype.Int8
	BaseSpeed     pgtype.Int8
	Species       pgtype.Text
	Description   pgtype.Text
	EvolutionNext []string
	EvolutionPrev []string
	Height        pgtype.Text
	Weight        pgtype.Text
	EggGroups     []string
	Abilities     []string
	Gender        pgtype.Text
	SpriteUrl     pgtype.Text
	ThumbnailUrl  pgtype.Text
	HiresUrl      pgtype.Text
}
