// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const listPokemon = `-- name: ListPokemon :many
select id, name_english, name_japanese, name_chinese, name_french, types, base_hp, base_attack, base_defense, base_sp_attack, base_sp_defense, base_speed, species, description, evolution_next, evolution_prev, height, weight, egg_groups, abilities, gender, sprite_url, thumbnail_url, hires_url from pokemon offset $1 limit $2
`

type ListPokemonParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) ListPokemon(ctx context.Context, arg ListPokemonParams) ([]Pokemon, error) {
	rows, err := q.db.Query(ctx, listPokemon, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pokemon
	for rows.Next() {
		var i Pokemon
		if err := rows.Scan(
			&i.ID,
			&i.NameEnglish,
			&i.NameJapanese,
			&i.NameChinese,
			&i.NameFrench,
			&i.Types,
			&i.BaseHp,
			&i.BaseAttack,
			&i.BaseDefense,
			&i.BaseSpAttack,
			&i.BaseSpDefense,
			&i.BaseSpeed,
			&i.Species,
			&i.Description,
			&i.EvolutionNext,
			&i.EvolutionPrev,
			&i.Height,
			&i.Weight,
			&i.EggGroups,
			&i.Abilities,
			&i.Gender,
			&i.SpriteUrl,
			&i.ThumbnailUrl,
			&i.HiresUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
