// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// GetPokemonResponse defines model for GetPokemonResponse.
type GetPokemonResponse = []Pokemon

// Pokemon defines model for Pokemon.
type Pokemon struct {
	// Abilities Abilities
	Abilities     *[]string `json:"abilities"`
	BaseAttack    *int64    `json:"base_attack"`
	BaseDefense   *int64    `json:"base_defense"`
	BaseHp        *int64    `json:"base_hp"`
	BaseSpAttack  *int64    `json:"base_sp_attack"`
	BaseSpDefense *int64    `json:"base_sp_defense"`
	BaseSpeed     *int64    `json:"base_speed"`
	Description   *string   `json:"description"`

	// EggGroups Egg groups
	EggGroups *[]string `json:"egg_groups"`

	// EvolutionNext Next evolution names
	EvolutionNext *[]string `json:"evolution_next"`

	// EvolutionPrev Previous evolution names
	EvolutionPrev *[]string `json:"evolution_prev"`
	Gender        *string   `json:"gender"`
	Height        *string   `json:"height"`
	HiresUrl      *string   `json:"hires_url"`
	Id            *int64    `json:"id"`
	NameChinese   *string   `json:"name_chinese"`
	NameEnglish   *string   `json:"name_english"`
	NameFrench    *string   `json:"name_french"`
	NameJapanese  *string   `json:"name_japanese"`
	Species       *string   `json:"species"`
	SpriteUrl     *string   `json:"sprite_url"`
	ThumbnailUrl  *string   `json:"thumbnail_url"`

	// Types Pokémon types
	Types  *[]string `json:"types"`
	Weight *string   `json:"weight"`
}

// GetPokemonParams defines parameters for GetPokemon.
type GetPokemonParams struct {
	// Offset Number of records to skip
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Maximum number of records to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get a list of Pokémon
	// (GET /pokemon)
	GetPokemon(ctx echo.Context, params GetPokemonParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetPokemon converts echo context to params.
func (w *ServerInterfaceWrapper) GetPokemon(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPokemonParams
	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPokemon(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/pokemon", wrapper.GetPokemon)

}
